version: "3.8"

services:
  csharp:  
    image: docker-instant-development/csharp:debug
    build:
      context: ./c#
      dockerfile: Dockerfile
      target: debug
      platforms:
        - "linux/amd64"
      args:
        - TARGETARCH=linux-musl-x64
    environment:
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8081:8080"
    volumes:
      - $PWD/c#/TodoApi:/src
    command: >
       /bin/sh -c "dotnet run"

  golang:
    image: docker-instant-development/golang-app:debug
    build:
      context: ./golang
      dockerfile: Dockerfile
      target: debug
    ports:
      - "8082:8080"
    volumes:
      - $PWD/golang:/src
    command: >
      /bin/sh -c "go run ."
      
  java:
    build:
      context: ./java
      dockerfile: Dockerfile
    ports:
      - "8083:8080"
    volumes:
      - $PWD/java:/app

  python:
    build:
      context: ./python
      dockerfile: Dockerfile
      target: debug
    ports:
      - "8084:8080"
    volumes:
      - $PWD/python:/src
    command: >
      /bin/sh -c "FLASK_APP=main.py python -m flask run --host=0.0.0.0 --port=8080"
      
  rust:
    build:
      context: ./rust
      dockerfile: Dockerfile
    ports:
      - "8085:8080"
    volumes:
      - $PWD/rust:/app

  nodejs:
    image: docker-instant-development/nodejs-app:debug
    build:
      context: ./nodejs
      dockerfile: Dockerfile
      target: debug
    ports:
      - "3000:3000"
    volumes:
      - $PWD/nodejs:/src
      - /src/node_modules
    command: >
      /bin/sh -c "npm start"